name: Deploy Backend to Heroku

on:
  push:
    branches:
      - main
    paths-ignore:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
      - "README.md"
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for secrets
        run: |
          python scripts/check_for_secrets.py
          if [ $? -ne 0 ]; then
            echo "::error::Potential secrets found in the codebase. Please review and fix before deploying."
            exit 1
          fi

      - name: Run tests
        run: |
          pytest

      - name: Deploy to Heroku
        id: deploy
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false
          healthcheck: "https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/health"
          checkstring: "healthy"
          delay: 5
          rollbackonhealthcheckfailed: true

      - name: Run database migrations
        if: steps.deploy.outcome == 'success'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          # Install Heroku CLI if not already installed
          if ! command -v heroku &> /dev/null; then
            curl https://cli-assets.heroku.com/install.sh | sh
          fi

          # Run database migrations
          heroku run --app ${{ secrets.HEROKU_APP_NAME }} "python -m scripts.init_db"

      - name: Set environment variables
        if: steps.deploy.outcome == 'success'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          # Set environment variables
          heroku config:set ENVIRONMENT=production --app ${{ secrets.HEROKU_APP_NAME }}
          heroku config:set GITHUB_ORG=${{ secrets.GITHUB_ORG || github.repository_owner }} --app ${{ secrets.HEROKU_APP_NAME }}
          heroku config:set GITHUB_REPO=${{ secrets.GITHUB_REPO || github.event.repository.name }} --app ${{ secrets.HEROKU_APP_NAME }}
